main:
  # - identifier: research
  #   name: "Research"
  #   url: "/research/"
  #   weight: 1
  - identifier: papers
    name: "Papers"
    url: "/papers/"
    weight: 2
  - identifier: blog
    name: "Blog"
    url: "/blog/"
    weight: 3

  # - identifier: about
  #   name: "About"
  #   url: "/about/"
  #   weight: 4
  - identifier: services
    name: "Services"
    url: "/services/"
    weight: 5
  - identifier: use-cases
    name: "Use Cases"
    url: "/use-cases/"
    weight: 6
  - identifier: demo
    name: "Risk Self-Check"
    url: "/demo/"
    weight: 7
  - identifier: contact
    name: "Contact Us"
    url: "/contact/"
    weight: 10